export type SchoolWordbookEntry = {
  word: string;
  meaning: string;
  phonetic?: string;
};

export type SchoolWordbookUnit = {
  name: string;
  words: SchoolWordbookEntry[];
};

export const SCHOOL_WORDBOOK_GROUP_NAME = "学校百词";

export const SCHOOL_WORDBOOK_UNITS: SchoolWordbookUnit[] = [
  {
    name: "学校百词 1/2",
    words: [
      { meaning: "王子", word: "prince" },
      { meaning: "仙女", word: "fairy" },
      { meaning: "为什么", word: "why" },
      { meaning: "因为", word: "because" },
      { meaning: "衣服", word: "clothes" },
      { meaning: "让", word: "let" },
      { meaning: "穿上", word: "put on" },
      { meaning: "在......以前", word: "before" },
      { meaning: "不得不，必须", word: "have to" },
      { meaning: "试穿", word: "try on" },
      { meaning: "合适，合身", word: "fit" },
      { meaning: "脱下", word: "take off" },
      { meaning: "蘑菇", word: "mushroom" },
      { meaning: "迟的，晚的", word: "late" },
      { meaning: "摘，拾", word: "pick" },
      { meaning: "明白，理解", word: "understand" },
      { meaning: "有害的", word: "be bad for" },
      { meaning: "留下，丢下", word: "leave behind" },
      { meaning: "离......远", word: "far from" },
      { meaning: "月亮", word: "moon" },
      { meaning: "街，街道", word: "street" },
      { meaning: "在......附近", word: "near" },
      { meaning: "城市", word: "city" },
      { meaning: "乘（汽车、火车等）", word: "by..." },
      { meaning: "公共汽车，巴士", word: "bus" },
      { meaning: "步行", word: "on foot" },
      { meaning: "地铁", word: "metro" },
      { meaning: "出租车，的士", word: "taxi" },
      { meaning: "自行车", word: "bike" },
      { meaning: "飞机", word: "plane" },
      { meaning: "轮船", word: "ship" },
      { meaning: "火车", word: "train" },
      { meaning: "骑车", word: "ride" },
      { meaning: "给......看", word: "show" },
      { meaning: "年幼的", word: "young" },
      { meaning: "篮子", word: "basket" },
      { meaning: "问路", word: "ask the way" },
      { meaning: "到达", word: "get to" },
      { meaning: "搭乘", word: "take" },
      { meaning: "上车", word: "get on" },
      { meaning: "车站", word: "station" },
      { meaning: "下车", word: "get off" },
      { meaning: "走，步行", word: "walk" },
      { meaning: "书店", word: "bookshop" },
      { meaning: "在......旁边", word: "next to" },
      { meaning: "太阳", word: "sun" },
      { meaning: "向......求助", word: "ask ... for help" },
      { meaning: "劳驾；对不起", word: "excuse me" },
      { meaning: "沿着，顺着", word: "along" },
      { meaning: "向右转", word: "turn right" },
      { meaning: "交通灯", word: "traffic light" },
      { meaning: "在你的右侧", word: "on your right" },
      { meaning: "电影院", word: "cinema" },
      { meaning: "医院", word: "hospital" },
      { meaning: "商店", word: "shop" },
      { meaning: "动物园", word: "zoo" },
      { meaning: "向左转", word: "turn left" },
      { meaning: "超市", word: "supermarket" },
      { meaning: "电影", word: "film" },
      { meaning: "车站", word: "stop" },
      { meaning: "满的；饱的", word: "full" },
      { meaning: "结束了，完了", word: "over" },
      { meaning: "看医生，看病", word: "see the doctor" },
      { meaning: "感觉，感到", word: "feel" },
      { meaning: "检查", word: "check" },
      { meaning: "应该", word: "should" },
      { meaning: "休息", word: "have a rest" },
      { meaning: "吃药", word: "take medicine" },
      { meaning: "喝水", word: "drink water" },
      { meaning: "牙疼", word: "toothache" },
      { meaning: "牙医", word: "dentist" },
      { meaning: "任何东西", word: "anything" },
      { meaning: "刷牙", word: "brush one's teeth" },
      { meaning: "就寝时间", word: "bedtime" },
      { meaning: "长颈鹿", word: "giraffe" },
      { meaning: "指着，指向", word: "point at" },
      { meaning: "脖子", word: "neck" },
      { meaning: "父或母", word: "parent" },
      { meaning: "擦，洗", word: "clean" },
      { meaning: "烧，煮", word: "cook" },
      { meaning: "扫地", word: "sweep the floor" },
      { meaning: "忙，忙碌", word: "busy" },
      { meaning: "洗碗", word: "wash the dishes" },
      { meaning: "整理床铺", word: "make the bed" },
      { meaning: "种植", word: "grow" },
      { meaning: "花园，果园", word: "garden" },
      { meaning: "甜的", word: "sweet" },
      { meaning: "害虫", word: "pest" },
      { meaning: "瓢虫", word: "ladybird" },
      { meaning: "走了，离开", word: "go away" },
      { meaning: "运动，比赛", word: "game" },
      { meaning: "有......气味，闻起来", word: "smell" },
      { meaning: "（猪、牛、羊等的）肉", word: "meat" },
      { meaning: "蔬菜", word: "vegetable" },
      { meaning: "西红柿，番茄", word: "tomato" },
      { meaning: "马铃薯，土豆", word: "potato" },
      { meaning: "我等不及了！", word: "I can't wait!" },
      { meaning: "找，寻找", word: "look for" },
      { meaning: "准备好", word: "ready" },
      { meaning: "好吃的，美味的", word: "yummy" },
      { meaning: "喜欢，喜爱", word: "love" },
      { meaning: "面包", word: "bread" },
      { meaning: "获胜，赢", word: "win" },
      { meaning: "太好了，太棒了", word: "yeah" },
      { meaning: "生气的，愤怒的", word: "angry" },
      { meaning: "斑，点", word: "spot" },
      { meaning: "抓，抓住", word: "catch" },
      { meaning: "赶走", word: "drive ... away" },
      { meaning: "节日", word: "festival" },
      { meaning: "春节", word: "Spring Festival" },
      { meaning: "一月", word: "January" },
      { meaning: "二月", word: "February" },
      { meaning: "叫作，称作", word: "call" },
      { meaning: "中国农历新年", word: "Chinese New Year" },
      { meaning: "团聚", word: "get together" },
      { meaning: "饺子", word: "jiaozi" },
      { meaning: "端午节", word: "Dragon Boat Festival" },
      { meaning: "五月", word: "May" },
      { meaning: "六月", word: "June" },
      { meaning: "地方，地点", word: "place" },
    ],
  },
  {
    name: "学校百词 2/2",
    words: [
      { meaning: "赛龙舟", word: "dragon boat race" },
      { meaning: "粽子", word: "rice dumpling" },
      { meaning: "中秋节", word: "Mid-Autumn Festival" },
      { meaning: "九月", word: "September" },
      { meaning: "十月", word: "October" },
      { meaning: "月饼", word: "moon cake" },
      { meaning: "重阳节", word: "Double Ninth Festival / Chongyang Festival" },
      { meaning: "十一月", word: "November" },
      { meaning: "老的，年纪大的", word: "old" },
      { meaning: "山，山脉", word: "mountain" },
      { meaning: "重阳糕", word: "rice cake" },
      { meaning: "母亲节", word: "Mother's Day" },
      { meaning: "父亲节", word: "Father's Day" },
      { meaning: "最喜欢的", word: "favourite" },
      { meaning: "生日", word: "birthday" },
      { meaning: "第十一", word: "eleventh" },
      { meaning: "第八", word: "eighth" },
      { meaning: "四月", word: "April" },
      { meaning: "一起", word: "together" },
      { meaning: "游戏", word: "game" },
      { meaning: "三月", word: "March" },
      { meaning: "七月", word: "July" },
      { meaning: "八月", word: "August" },
      { meaning: "十二月", word: "December" },
      { meaning: "英雄", word: "hero" },
      { meaning: "戏，戏剧", word: "play" },
      { meaning: "数字，数", word: "number" },
      { meaning: "密码", word: "password" },
      { meaning: "答案", word: "answer" },
      { meaning: "第四", word: "fourth" },
      { meaning: "开始", word: "start" },
      { meaning: "打仗，打架", word: "fight" },
    ],
  },
];

export const SCHOOL_WORDBOOK_WORD_COUNT = SCHOOL_WORDBOOK_UNITS.reduce(
  (total, unit) => total + unit.words.length,
  0
);
