/**
 * Static mapping of sentence unit names to their full sentence text.
 * Organized by book (group_name) -> unit_name -> "English\nChinese"
 */

type SentenceMap = Record<string, Record<string, string>>;

export const SENTENCE_DATA: SentenceMap = {
  "新东方小学1200词": {
    "Sentence 01": "It's time for us to have lunch.\n我们该吃午饭了。",
    "Sentence 02": "She had an egg, a piece of bread and some milk for breakfast.\n她早餐吃了一个鸡蛋、一片面包，还喝了一些牛奶。",
    "Sentence 03": "Which fruit do you like, apples or oranges?\n你喜欢哪种水果，苹果还是橘子？",
    "Sentence 04": "The fish soup tasted so good that the guests asked for more.\n这道鱼汤味道很好，客人们要求再来一点。",
    "Sentence 05": "She usually gets up at half past seven in the morning.\n她通常早上七点半起床。",
    "Sentence 06": "My grandpa used to have a walk in the garden after supper.\n我爷爷过去常常在晚饭后在花园里散步。",
    "Sentence 07": "At weekends, some people like to stay at home, but others like to go for a walk or have a picnic.\n在周末，一些人喜欢待在家里，然而另一些人喜欢去散步或野餐。",
    "Sentence 08": "I called you yesterday evening, but there was no answer.\n昨晚我给你打电话了，但没人接。",
    "Sentence 09": "On Saturday, I will help my mom with the housework.\n周六，我要帮妈妈做家务。",
    "Sentence 10": "The children are listening to the radio while they are cleaning the windows.\n孩子们一边擦窗户一边听广播。",
    "Sentence 11": "She was making dinner when the phone rang.\n她正在做晚饭的时候，电话响了。",
    "Sentence 12": "After lunch, Ann cleaned the table and washed dishes.\n午饭后，安清理了桌子，洗了碗。",
    "Sentence 13": "I'll learn about cooking on the Internet.\n我要在网上学习烹饪。",
    "Sentence 14": "Chinese people are very good at table tennis, and it's our favorite sport.\n中国人很擅长打乒乓球，这是我们最喜欢的运动。",
    "Sentence 15": "He is one of the tallest basketball players in the world.\n他是世界上最高的篮球运动员之一。",
    "Sentence 16": "He's going to the nearby valley to take part in a mountain bike race.\n他要去附近的山谷参加一个山地自行车比赛。",
    "Sentence 17": "My favourite subject is science because I can do experiments during the class.\n我最喜欢的科目是科学课，因为我可以在课堂上做实验。",
    "Sentence 18": "To make your dream come true, you should study hard.\n为了实现你的梦想，你应该努力学习。",
    "Sentence 19": "We learned from each other in and out of class.\n我们在课堂内外互相学习。",
    "Sentence 20": "This dictionary was very cheap and it only cost me twelve dollars.\n这本字典很便宜，只花了我12美元。",
    "Sentence 21": "There are some books, a pen and a pencil on the desk.\n桌子上有一些书、一支钢笔和一支铅笔。",
    "Sentence 22": "They have four lessons in the morning and two in the afternoon.\n他们上午上四节课，下午上两节课。",
    "Sentence 23": "Our class teacher asked the monitor why Bill didn't come to school.\n我们的班主任问班长为什么比尔没有来上学。",
    "Sentence 24": "Miss Green taught us English four years ago.\n格林小姐四年前教我们英语。",
    "Sentence 25": "Tom never forgets to turn off the lights when he leaves the classroom.\n汤姆离开教室时从不忘记关灯。",
    "Sentence 26": "I finished doing my homework and then I had a rest.\n我做完家庭作业，然后休息了一下。",
    "Sentence 27": "Wish you every success in your exams.\n祝你考试成功。",
    "Sentence 28": "Jane was sure that she had left her wallet in the classroom.\n简很确信自己把钱包落在教室里了。",
    "Sentence 29": "It's said that our school's paper comes out once a week.\n据说我们的校报每周出版一次。",
    "Sentence 30": "I think our school life is full of laughing.\n我认为我们的校园生活充满了欢声笑语。",
    "Sentence 31": "We're going to leave our primary school soon and start middle school this September.\n我们很快就要离开我们的小学，在今年九月开始上中学。",
    "Sentence 32": "I like football, reading, swimming and singing songs.\n我喜欢踢足球、看书、游泳和唱歌。",
    "Sentence 33": "It's very hot in summer, so I like to go swimming.\n夏天很热，所以我喜欢去游泳。",
    "Sentence 34": "Listen! The girls are singing in the music room.\n听！女孩们正在音乐教室唱歌。",
    "Sentence 35": "She began to learn the piano at the age of five.\n她五岁开始学钢琴。",
    "Sentence 36": "Here is a story about air and water.\n这是一个关于空气和水的故事。",
    "Sentence 37": "We will have an English party next Sunday.\n下周日，我们将举办英语派对。",
    "Sentence 38": "We gave Mum a surprising party on her fortieth birthday.\n在妈妈四十岁生日那天，我们为她举办了一个惊喜的派对。",
    "Sentence 39": "This morning, Tina and I flew my new kite in the park, but it wasn't windy in the park.\n今天早上，我和蒂娜在公园里放了我的新风筝，但公园里没有风。",
    "Sentence 40": "It's very kind of you to help me get the ticket for the concert.\n你帮我买到了这个音乐会的票真是太好了。",
    "Sentence 41": "The students couldn't help laughing when they heard the joke.\n听到这个笑话，学生们忍不住笑了起来。",
    "Sentence 42": "We were tired so we stayed at home.\n我们累了，所以我们待在家里。",
    "Sentence 43": "I was very curious about how he spent his money.\n我很好奇他是如何花钱的。",
    "Sentence 44": "Tom was in a blue mood, because he lost the race.\n汤姆情绪低落，因为他输了比赛。",
    "Sentence 45": "We are going to invite my uncle, aunt and cousins for dinner.\n我们将邀请我的叔叔、婶婶和堂兄弟共进晚餐。",
    "Sentence 46": "Thanks for your invitation to have dinner, but I can't come.\n谢谢你邀请我共进晚餐，可是我来不了。",
    "Sentence 47": "I'm sorry to hear that.\n听到这件事我很难过。",
    "Sentence 48": "On each shelf, the books are lined up in order from smallest to largest.\n在每个书架上，按从小到大的顺序排列摆放图书。",
    "Sentence 49": "When we arrived at Ted's house, his dog Guinness welcomed us.\n当我们到达特德家时，他的狗吉尼斯来欢迎我们。",
    "Sentence 50": "Jack, a close friend of mine, will come and join us in the game.\n杰克，我的一个好朋友，会来和我们一起玩游戏。",
    "Sentence 51": "The one my dad carried is my older sister, Tina.\n我爸爸抱着的人是我的姐姐蒂娜。",
    "Sentence 52": "I want to be a doctor like my mom and help more people.\n我想成为像我妈妈一样的医生，帮助更多的人。",
    "Sentence 53": "It's very nice of you to write to me.\n你给我写信真是太好了。",
    "Sentence 54": "The new teacher is short, with big eyes.\n新老师个子不高，眼睛很大。",
    "Sentence 55": "We all like him because he says little but does much.\n我们都喜欢他，因为他说得少，但做得多。",
    "Sentence 56": "Joey's hair is a little shorter than Daisy's.\n乔伊的头发比黛西的短一点。",
    "Sentence 57": "The man was poor but he was honest.\n这个男人很穷，但是他很诚实。",
    "Sentence 58": "Many people don't like shopping on the Internet because they can't see the things or try the clothes on.\n许多人不喜欢网上购物，因为他们不能看到商品或试穿衣服。",
    "Sentence 59": "Ben has two pairs of sports shoes but they're old.\n本有两双运动鞋，但是它们都旧了。",
    "Sentence 60": "She put on her favorite orange dress.\n她穿上了她最喜欢的橙色连衣裙。",
    "Sentence 61": "She has a nice pair of pink gloves.\n她有一副漂亮的粉红色手套。",
    "Sentence 62": "It's traditional to eat moon cakes on Mid-Autumn Day in China.\n中秋节吃月饼是中国的传统。",
    "Sentence 63": "My mother will take me to the World Park to learn about the famous places around the world tomorrow.\n我妈妈明天要带我去世界公园了解世界各地的著名景点。",
    "Sentence 64": "Last summer vacation I went to Beijing with my parents.\n去年暑假，我和父母一起去了北京。",
    "Sentence 65": "We went to the Science Museum last Saturday.\n上周六，我们去了科学博物馆。",
    "Sentence 66": "When we cross the road, we must follow the traffic rules.\n我们过马路时，一定要遵守交通规则。",
    "Sentence 67": "To keep safe, you can wait on the pavement and look out for cars and bikes.\n为了保证安全，你可以在人行道上等待，并且当心汽车和自行车。",
    "Sentence 68": "You must not play football on the road because there are many cars and bikes.\n你不能在路上踢足球，因为路上有很多汽车和自行车。",
    "Sentence 69": "Let's meet at the bus stop at 8 o'clock.\n我们八点在公交车站见面吧。",
    "Sentence 70": "Maybe you can ride a bike or take a bus instead of driving a car.\n或许你可以骑自行车或乘公共汽车，而不是开车。",
    "Sentence 71": "It takes us half an hour to walk to school every day.\n我们每天步行去学校要花半个小时。",
    "Sentence 72": "The train from Tianjinnan arrived an hour ago.\n从天津南开来的火车一小时前就到了。",
    "Sentence 73": "You can go down the street and then turn right at the first corner.\n你可以沿着这条街走，然后在第一个拐角处右转。",
    "Sentence 74": "We mustn't talk or speak loudly in public places like hospitals, libraries or cinemas.\n我们不能在医院、图书馆或电影院等公共场所大声讲话。",
    "Sentence 75": "Hainan is in the south of China.\n海南位于中国的南部。",
    "Sentence 76": "The bookstore is next to the library.\n书店紧邻图书馆。",
    "Sentence 77": "My grandma lives with my uncle in a village not too far away.\n我奶奶和我叔叔住在不太远的一个村子里。",
    "Sentence 78": "Sitting for a long time at the computer is bad for our health.\n在电脑前久坐对我们的健康有害。",
    "Sentence 79": "People often need to take some medicine when they catch a cold or a cough.\n当人们感冒或咳嗽时，通常需要吃一些药。",
    "Sentence 80": "It will be cold and windy in Xi'an and it will be sunny and warm in Sanya.\n西安天气寒冷、有风，三亚天气晴朗、温暖。",
    "Sentence 81": "The weather is very hot, so the ice turns into water.\n天气很热，所以冰变成了水。",
    "Sentence 82": "The weather forecast says it will be rainy in the late afternoon.\n天气预报说下午晚些时候会下雨。",
    "Sentence 83": "People plant trees in spring and farmers are busy harvesting in autumn.\n人们在春天种树，农民们在秋天忙着收获。",
    "Sentence 84": "When spring comes, the animals that sleep in winter start waking up.\n春天来临时，冬眠的动物开始苏醒。",
    "Sentence 85": "What a big elephant it is!\n好大的一头象啊！",
    "Sentence 86": "You can see as many as 15,000 butterflies sitting on one branch!\n你可以看到多达15,000只蝴蝶栖息在一根树枝上！",
    "Sentence 87": "Joy keeps two pets at home and she feeds them after dinner every day.\n乔伊在家里养了两只宠物，她每天晚饭后给它们喂食。",
    "Sentence 88": "It's your turn to walk the dog.\n轮到你去遛狗了。",
    "Sentence 89": "The girl wants to buy a flower for her mum.\n这个女孩想给她的妈妈买一朵花。",
    "Sentence 90": "Now there are only about ten thousand blue whales in the wild.\n现在野生蓝鲸只有大约一万只。",
    "Sentence 91": "Most of the kids have never seen the sea.\n这些孩子中的大多数从没见过大海。",
    "Sentence 92": "The moon is round and bright on that day.\n那天的月亮又圆又亮。",
    "Sentence 93": "The moon goes around the earth all the time.\n月球一直绕着地球转。",
    "Sentence 94": "We shouldn't leave the rubbish anywhere.\n我们不应该到处扔垃圾。",
    "Sentence 95": "We should not cut down too many trees because trees help keep the air clean.\n我们不应该砍伐太多的树木，因为树木有助于保持空气清洁。",
    "Sentence 96": "We use plastic to make bags and bottles, but too much plastic is bad for the Earth.\n我们用塑料制作袋子和瓶子，但是过多的塑料对地球有害。",
    "Sentence 97": "We should not drive so much because cars use a lot of energy.\n我们不应该开车太频繁，因为汽车会消耗大量的能源。",
    "Sentence 98": "Robots can cheer up sick kids, too.\n机器人还能让生病的孩子开心起来。",
    "Sentence 99": "We're going to see a film about space travel!\n我们要去看一场关于太空旅行的电影！",
    "Sentence 100": "They will travel to Mars in a Time Chair.\n他们将乘坐时光椅去火星旅行。",
  },

  "新东方初中2000词": {
    "Sentence 01": "The more people follow an idea, the better or truer we think the idea is.\n遵循某种想法的人越多，我们就会认为这个想法越好或越",
    "Sentence 02": "With its black-white coat, the animal is one of the most precious animals in the world.\n这种动物有黑白相间的皮毛，是世界上最珍贵的动物之",
    "Sentence 03": "Making choices can often be difficult for many people since they often over-complicate very simple decisions.\n对许多人而言，做出选择往往是困难的，因为他们通常会",
    "Sentence 04": "Detective stories have been popular since Conan Doyle wrote his famous stories about great detective Sherlock Holmes.\n自从柯南·道尔写了关于大侦探夏洛克·福尔摩斯的著名小",
    "Sentence 05": "The moveable type printing, the compass, gun powder and the paper-making are called four great inventions of China.\n活字印刷术、指南针、火药和造纸术被称作“中国四大发",
    "Sentence 06": "If the earth has more trees, greenhouse gases will be reduced, and this will help stop global warming.\n如果地球上有更多的树木，温室气体就会减少，从而有助",
    "Sentence 07": "Living things seem to be staying within the wave, moving slowly inside it as if they were weightless.\n生物似乎存在于海浪中，在海浪中慢慢移动，就好像失重",
    "Sentence 08": "Cars powered by gasoline were sold for many years before hybrid vehicles that use gasoline, electricity, and solar energy.\n在使用汽油、电力及太阳能的混合动力车面世之前，以汽",
    "Sentence 09": "Good friendships are not easy to develop, but a friendship can last forever if you are loyal and sincere.\n良好的友谊不容易培养，但是如果你忠实且真诚，友谊就",
    "Sentence 10": "When the tide rises, water comes through the dam, the turbines turn and the electric generators work, producing electricity.\n涨潮的时候，水流进大坝，推动涡轮机转动，从而带动发",
    "Sentence 11": "Those special tastes can immediately unlock a whole flood of emotions, memories and feelings of family, love, and comfort.\n那些特别的味道能立即释放出大量的关于家庭、爱和慰藉",
    "Sentence 12": "Guana always invites everyone to school parties, including those who clean the floors and those who drive the school buses.\n瓜纳总是会邀请每个人去参加学校聚会，包括那些扫地的",
    "Sentence 13": "Beauty sleep is a real thing, and researches have shown that people who have enough sleep look more attractive to others.\n美容觉是真实存在的，研究表明睡眠充足者的外表对别人",
    "Sentence 14": "Keeping family recipes is saving and honoring our tradition so that future generations can continue to make family ties stronger.\n保留家庭食谱是对我们传统的保留和尊重，这样子孙后代",
    "Sentence 15": "Not only are bananas sweet and delicious, but they are easy to carry around, so you can take them anywhere.\n香蕉不仅香甜可口，而且易于携带，所以你可以把它们带",
    "Sentence 16": "What parents can learn from these studies is to listen calmly without getting angry right away when their child confesses.\n父母从这些研究中可以学到的是，当他们的孩子坦白的时",
    "Sentence 17": "These researchers show that great white sharks are dangerous hunters which will attack anything that looks and acts like a fish.\n这些研究人员表示：大白鲨是危险的猎手，它们会攻击任",
    "Sentence 18": "The only time most of us ever learn about unlocking our self- improvement power is when the whole world is falling apart.\n我们大多数人只有当自己的整个世界崩塌的时候才学会释",
    "Sentence 19": "By understanding the psychological processes behind our different experiences of time, we might be able to slow down time a little.\n通过了解我们不同的时间体验背后的心理历程，我们也许",
    "Sentence 20": "The more hours you don’t sleep, the more hours you should sleep to “pay back” the hours on your “sleep credit card”.\n你不睡觉的时间越多，你就应该睡更多的觉用以“还清”你",
    "Sentence 21": "Drones can do a lot of things for us, taking photos, delivering things from packages to pizzas to beer and following wild animals.\n无人机能为我们做很多事情，拍照、运送东西（从运输包",
    "Sentence 22": "There was no modern technology at that time, yet the items that people had were quite enough for them to live their lives.\n当时没有现代技术，但是人们所拥有的物品足够他们生活",
    "Sentence 23": "The findings show that long-term exposure to greenness is positively associated with white and grey matter volumes in several parts of the brain.\n研究结果表明，长期接触绿色环境与大脑多个部位的灰白",
    "Sentence 24": "We often reach a point in our life when we should be ready for change that will help us unlock our self-improvement power.\n我们在生活中经常会遇到这样的时刻：我们应该为改变做",
    "Sentence 25": "To travel by bus is easy, cheap and convenient, though not so fast as travelling by plane or so comfortable as by train.\n坐大巴车旅行简单、便宜且便捷，虽然没有坐飞机旅行那",
    "Sentence 26": "No matter why there is growing interest in self-help books, it’s good to know that help is at hand if we need it.\n不管为什么人们对自助书籍的兴趣与日俱增，我们最好知",
    "Sentence 27": "After hearing about sacrifices made by firemen, she was moved by the risks they faced, so Savannah made 200 thank-you cards for them.\n得知消防员做出的牺牲后，萨凡纳被他们面临的危险所感",
    "Sentence 28": "Researchers changed the make-up of short and long wavelength light, which provided a small difference in brightness, as well as changes in color.\n研究人员改变了短波长和长波长的光的构成，用这种方法",
    "Sentence 29": "You will adopt a certain type of behavior, dress, or attitude in order to be accepted as part of a group of your “peers”.\n你将采取某种行为、着装或态度，以便被你的“同龄人”群",
    "Sentence 30": "For teens, as school and other activities take you away from home, you may spend more time with your friends than with your family.\n对于青少年来说，由于学校和其他活动让你走出家门，你",
    "Sentence 31": "The researchers discovered that the number of risks teens took more than doubled when their friends were watching, compared with when they played alone.\n研究人员发现，与独自玩游戏相比，有朋友在场观看时，",
    "Sentence 32": "The world’s longest cross-sea bridge—the Hong Kong-Zhuhai- Macao Bridge is considered as “one of the seven wonders of the modern world” by some people.\n一些人认为世界上最长的跨海大桥——港珠澳大桥是“现",
    "Sentence 33": "The Reader also tells us if we understand what we are reading, we will know what reading really is and we’ll become better readers.\n《朗读者》(电视节目)也告诉我们，如果我们理解自己在",
    "Sentence 34": "The Internet has also made it easier for people to share different types of beauty since people are always posting pictures on social media.\n互联网也使得人们更容易分享不同类型的美，因为人们总",
    "Sentence 35": "However, when teenagers make decisions in the heat of the moment or in social situations, their decisions are often influenced by factors like peers.\n然而，当青少年在盛怒之下或在社交场合做决定时，他们",
    "Sentence 36": "However, the National Parks in England include places where people live and work, as well as wild areas where there are few human activities.\n然而，英国的国家公园包括人们生活和工作的地方，以及",
    "Sentence 37": "The United Nations is an international organization, which is meant to encourage countries to work together on different opinions without the use of war.\n联合国是一个国际组织，旨在鼓励各国在不动用武力的情",
    "Sentence 38": "Some trains on the Beijing-Zhangjiakou line are “smart” as they provide 5G signals and wireless charging for passengers, as well as intelligent lighting.\n北京至张家口线路的部分列车为“智能”列车，因为这些列",
    "Sentence 39": "Experts say that young people might find the social restrictions on seeing their friends in real life stressful, which is why technology can be helpful.\n专家称，年轻人可能会发现在现实生活中对约见朋友社交",
    "Sentence 40": "By understanding the ocean, scientists can prevent this breakup of ships by predicting when the water will be too dangerous for people and their ships.\n通过了解海洋，科学家们能够预测什么时候水域对人们和",
    "Sentence 41": "If voices get too loud or it appears that someone is angry, the mediator will speak up and have them treat each other with respect.\n如果有人说话声音太大或者有人似乎生气了，调解人会发",
    "Sentence 42": "Researchers have discovered that, in general, it only takes seven seconds for a person to start making judgments about you when they first meet you.\n研究人员发现，一般而言，当一个人初次见到你时，他只",
    "Sentence 43": "Mobile technology means we can hold the world in our hands, however, when it comes to technology and health care, opportunities and challenges come together.\n移动技术意味着我们可以掌控世界，然而，当谈到技术和",
    "Sentence 44": "The strangers were good at judging if the person they were looking at was tired, and, if they were sleepy, their attractiveness score was low.\n陌生人擅长判断他们所观察的人是否累了，如果他们困倦",
    "Sentence 45": "I’d rather be this girl who is able to forgive, love and act, even if it means being disappointed or being hurt again and again.\n我宁愿做一个能够原谅、去爱并付出行动的女孩，即使这",
    "Sentence 46": "Once you’ve thought about the subjects and activities you like best, the next step is to look for careers that put those interests to use.\n一旦你想好了你最喜欢的科目和活动，下一步就是去寻找",
    "Sentence 47": "Only when we are enjoying the whole process of unlocking our self-improvement power will we realize that we’re beginning to take things light and become happy.\n只有当我们正在享受释放自我提升力量的全过程时，我们",
    "Sentence 48": "To celebrate the day, people usually climb mountains and enjoy chrysanthemum, so the festival is also known as the Height Ascending Festival or the Chrysanthemum Festival.\n为了庆祝这一天，人们通常会爬山、赏菊，所以这个节日",
    "Sentence 49": "Every time you remember your loved ones, recreate one of the dishes from your collection and let the memories from the good old days comfort you.\n每当你想起自己所爱的人时，就再做一道你收藏的菜谱中",
    "Sentence 50": "Firstly, food is often thrown away before it reaches customers because too much of it is produced, or because it is not kept properly in farms.\n首先，在送到顾客面前之前，食物经常因为产量过高或者",
    "Sentence 51": "At Qinghe Railway Station in Beijing, China’s first visual remote ticket vending machine has been installed to help passengers who are not able to afford tickets online.\n北京清河火车站安装了中国第一台远程可视售票机，以帮",
    "Sentence 52": "Mischel got in touch with the children and found that those with strong willpower were getting better marks at university, were better behaved and were more popular.\n米歇尔跟那些孩子保持着联系，她发现那些意志坚定的孩",
    "Sentence 53": "But of course, it’s also a good choice for you to walk along the wooden roads and enjoy natural sights around if you are not so brave.\n当然，如果你没那么勇敢的话，沿着木制路，欣赏周围的",
    "Sentence 54": "The best thing about gesturing during a phone call is that no one can see what you’re doing, so you can gesture as wildly as you like!\n打电话时做手势最大的好处在于没人能看到你正在做什",
    "Sentence 55": "As long as the older forms of knowledge are stored somewhere in our networks, and can be found when we need them, perhaps they’re not really forgotten.\n只要旧的知识被存储在我们大脑网络中的某个地方，并且",
    "Sentence 56": "We must answer the phone in 3 seconds, get clear information about the patient in 60 seconds and dispatch emergency medical workers in 3 minutes at most.\n我们必须在3秒钟内接听电话，60秒内得到病人的确切信",
    "Sentence 57": "Another study of 2,593 children shows that children in schools with more green space have a greater increase in working memory and a greater decrease in inattentiveness.\n另一项对2,593名儿童的研究表明，在绿地面积较大的学校",
    "Sentence 58": "Lara thought it was terrible to get up early in the morning, while Tara insisted that mornings were fresh and it was difficult to stay up till midnight.\n劳拉认为早上早起很讨厌，而塔拉坚持认为早晨很凉爽且",
    "Sentence 59": "Everyone was very nervous, but the owner Smith was as cool as a cucumber—he just crawled back out, put the dog on its lead, and went home.\n每个人都很紧张，但是主人史密斯却镇定自若，他倒退着",
    "Sentence 60": "Lifelong exposure to green space in the living places was recorded—using the information on the children’s addresses from birth up through to the time of the study.\n该研究使用从出生到研究期间儿童住址的信息，记录他们",
    "Sentence 61": "Food waste is a growing problem and we, either farmers or food sellers or customers, must take this problem more seriously and do what we can to help.\n食物浪费是一个日益严重的问题，无论是农民，还是食品",
    "Sentence 62": "I’d rather be crazy than be the kind of person who wouldn’t cry when the situation called for it, or who wouldn’t let herself feel anything at all.\n我宁愿疯狂，也不愿做那种在情势所需时不哭的人，或者",
    "Sentence 63": "I read the articles slowly, like a careful student, with mixed feelings as well—my kid, who followed me around not long ago, has now become my teacher!\n我慢慢地读着文章，像一个细心的学生，也怀着复杂的心",
    "Sentence 64": "Second, to make way for the golf course, lots of playground equipment will have to be moved or knocked down, which is a waste of time and money.\n其次，为了给高尔夫球场腾出空间，许多游乐场的器材都",
    "Sentence 65": "To remember her best friend who died of cancer nearly 10 years ago, Fredette decided to serve those in Orange County who are less lucky than she is.\n为了纪念她十年前死于癌症的挚友，弗雷黛特决定为那些",
    "Sentence 66": "At the first London Marathon, just 6,225 people completed the course, and since then it has grown into one of the most important sporting events in the world.\n在第一届伦敦马拉松比赛中，只有6,225人跑完了全程，从",
    "Sentence 67": "With schools closed and restrictions on public activities, it can be a difficult time for young people, who suddenly can’t spend time with their friends and family in person.\n由于学校停课，公共活动受限，年轻人突然无法面对面地",
    "Sentence 68": "It is easy to be a friend when everything is going great, but a true friend is one who sticks around in both the good times and the bad.\n当一切都很顺利的时候，做朋友是很容易的，但是真正的",
    "Sentence 69": "Most kids that age would be picking out candies or toys in a store for themselves, instead of helping their mom pick out fruits, as the two kids did.\n大多数那个年龄段的孩子会在商店里为自己挑选糖果或玩",
    "Sentence 70": "If you don’t want to criticize your child when they forget, it is important to remind them when you see them with their hands around their face or mouth.\n如果你不想在孩子忘记时批评他们，那么当看到他们用手",
    "Sentence 71": "At first, the ancient people looked up at the sun and could tell it was the middle of the day when the sun was directly overhead in the sky.\n起初，古时候的人们抬头看太阳，如果太阳正好当头照，",
    "Sentence 72": "I believe that my grandma is a star watching over me, and she would have wanted me to be strong and happy like her, even though there are bad times.\n我相信我奶奶就像星星一样守护着我，尽管会遇到一些艰",
    "Sentence 73": "If you pointed to any book on my shelves, I could name the year I got it, where I was working, and probably where I was living at the time.\n如果你指向我书架上的任何一本书，我都能说出是哪一年",
    "Sentence 74": "I’m also not as sensitive as I used to be—getting an impolite customer might make me feel bad, but very soon I can laugh it off with my co-workers.\n我也不再像以前那样敏感了，一个不礼貌的顾客可能会让",
    "Sentence 75": "Shang Yang was a statesman and worked out many reforms for the state, like paying more attention to farming and giving rewards to soldiers who were successful when at war.\n商鞅是一位政治家，他为国家制订了许多项改革措施，比",
    "Sentence 76": "Dr. Dadvand’s study also adds to the proof that suggests the lasting effects of early life exposure to greenness on our health and the benefits of increasing greenness in cities.\n戴德万德博士的研究也进一步证明了早期接触绿色环境对",
    "Sentence 77": "At one point or another, we are all going to finally unlock our self-improvement power not because the world says so, but because we realize it’s for our own good.\n在人生的某些时刻，我们最终都会释放自我提升的力量，",
    "Sentence 78": "For example, if you smile, your voice will sound warm and friendly; just the opposite, if you have an angry look on your face, it can make you sound unpleasant.\n例如，如果你微笑，你的声音就会听起来热情友好；恰恰",
    "Sentence 79": "A teen might join in a volunteer project because his or her friends are doing it, or get good grades because his or her friends think getting good grades is important.\n青少年可能会因为朋友正在参与的一个志愿者项目而加入",
    "Sentence 80": "To feed the seven billion people on Earth, most farmers today are growing only species of plants and farming only species of animals that are easy to produce in large numbers.\n为了养活地球上70亿人口，现在大多数农民只种植高产的",
    "Sentence 81": "If Bella can teach at least one person to care for all living things, no matter how big or how small, then we have done what we have set out to.\n如果贝拉（松鼠）能教会至少一个人去关心所有的生物，",
    "Sentence 82": "At the moment of 9:43 a.m., on Tuesday, June 23rd, 2020, at the Xichang Satellite Launch Center in Sichuan Province, the last satellite of the third-generation network was sent into space.\n2020年6月23日，星期二，上午9:43，在四川省西昌卫星发",
    "Sentence 83": "Computers would have difficulties making ethical decisions: if a child ran into the road, would the computer choose to hit the child or turn suddenly and potentially kill the car’s passengers?\n电脑很难做出合乎道德的决定：如果一个孩子跑到马路",
    "Sentence 84": "Among the high-quality treasures, the writing brush produced in Huzhou, the ink stick produced in Huizhou, the xuan paper made in Xuancheng and the ink stone made in Duanxi are the best-known.\n在众多优质珍品中，湖州的毛笔、徽州的墨条、宣城的宣",
    "Sentence 85": "I threw the big jacket on my brother’s bed and looked at it for a long time before I put it on and went out, smiling a “thank you” to my mom.\n我把那件大的夹克扔到哥哥床上，看了很久才穿上它，然",
    "Sentence 86": "When someone without a medical degree sees a flagged result with no explanation on the website, there’s room for all kinds of stories to form in their minds—and also great worry.\n当一个没有医学文凭的人在网上看到一个没有任何解释的",
    "Sentence 87": "However, my family is very big on having a traditional career and so when I said that I wanted to go to college and study writing, my parents told me that I couldn’t.\n然而，我的家庭非常喜欢传统职业，所以当我说我想在大",
    "Sentence 88": "They support female soldiers, raise money through their efforts, teach other kids about life lessons, and use their free time to care for the old trees we love so dearly in the community.\n他们支持女兵通过自身努力筹集资金，教授其他孩子生活",
    "Sentence 89": "From the pile of books on your bedside table to your well- organized shelves, whether we notice it or not, our book collections are telling a story before a single page has been turned.\n从你床头柜上的一堆书到井然有序的书架，不管我们是否",
    "Sentence 90": "It was last January, when I’d just finished a charity and was on the train back home, that I put down my phone and started writing thank-you notes to people who had helped.\n去年一月，我刚完成一项慈善活动，在回家的火车上，我",
    "Sentence 91": "Liao Yifeng, a police officer, working in a small village in Wuhan, is a father to thirty nine “Left-behind” children, whose parents are working far away from home and seldom spent time with them.\n警察廖依峰在武汉一个小村庄工作，他是39个留守儿童的",
    "Sentence 92": "Objects, like bits of old space rockets or satellites, move around the planet at very high speeds, so fast that even a very small piece can break important satellites or become dangerous to astronauts.\n一些物体，像旧的太空火箭或卫星的碎片，以非常快的速",
    "Sentence 93": "Within ten years, the Lindy Hops was sweeping through the United States and became a symbol of unity, as young people of all racial backgrounds crowded into dance halls to swing the night away.\n在十年间，林迪舞风靡美国，且成为团结的象征，因为不",
    "Sentence 94": "According to a report on the World Economic Forum(2016), critical thinking, creativity, and their practical application are widely accepted as the top three skills that young people need to possess in their future career.\n根据2016年世界经济论坛的一份报告，批判性思维、创造",
    "Sentence 95": "These writers teach you how to deal with problems in your life, for example, how to get on well with your classmates or friends, how to plan your time well or how to find happiness.\n这些作家教你如何应对生活中的问题，例如，如何与你的",
    "Sentence 96": "Wouldn’t it be wonderful to be able to walk out into a garden high above the city’s noise and traffic, whether you’re at school or in an office or just at home in a ten-floor block?\n无论你是在学校，在办公室，还是在十层楼的家里，只要",
    "Sentence 97": "Self-improvement may not be everybody’s favorite word, but if we look at things in a different way, we might have greater chances of enjoying the whole process instead of counting the days until we are fully improved.\n自我提升可能不是每个人都喜欢的字眼，但是如果我们换",
    "Sentence 98": "When someone feels stressed from his or her teachers or parents, your smile is like the sun breaking through the clouds; your smile can help him or her realize that all is hopeful—that there is still joy in the world.\n当一个人感到来自老师或父母的压力时，你的微笑就像冲",
    "Sentence 99": "If you go shopping in any toy store, you can see clearly the different games and toys for boys and girls: there are a lot of pink toys on one side of the store for girls; and dark-colored cars, guns, and soldiers for boys.\n如果你去任何一家玩具店购物，你都能清楚地看到提供给",
    "Sentence 100": "There are several ways that can help us sleep better, such as avoiding drinks that make us excited late in the day, going to sleep at the same time each night, and sleeping in a comfortable place that is dark, quiet and warm.\n有几种方法可以帮助我们睡得更好，比如远离那些使我们在深夜兴奋的饮料，每晚在同一时间点去睡觉，睡在一个昏暗、安静、温暖且舒适的地方。",
  },

  "新东方高中7000词": {
    "Sentence 01": "Essentially, a theory is an abstract, symbolic representation of what is conceived to be reality.\n理论在本质上是对人们构想的现实的一种抽象和符号化的表",
    "Sentence 02": "Thanks to modern irrigation, crops now grow abundantly in areas where once nothing but cacti and sagebrush could live.\n受当代灌溉设施之赐，在原来只有仙人掌和灌木蒿才能生存的",
    "Sentence 03": "Anthropologists have discovered that fear, happiness, sadness, and surprise are universally reflected in facial expressions.\n人类学家们已经发现，恐惧、快乐、悲伤和惊奇会反映在面部",
    "Sentence 04": "Of the millions who saw Haley’s Comet in 1986, how many people will live long enough to see it return in the twenty-first century.\n1986年看见哈雷慧星的千百万人当中，有多少人能够长寿到足",
    "Sentence 05": "The greater the population there is in a locality, the greater the need there is for water, transportation, and disposal of refuse.\n一个地方的人口越多，其对水、交通和垃圾处理的需求就会越",
    "Sentence 06": "Perfectly matched pearls, strung into a necklace, bring a far higher price than the same pearls sold individually.\n完美搭配的珍珠串成一条项链，能带来比单颗售卖高得多的价",
    "Sentence 07": "The development of mechanical timepieces spurred the search for more accurate sundials with which to regulate them.\n机械计时器的发展促使人们寻求更精确的日晷，以便校准机械",
    "Sentence 08": "Studies of the gravity field of the Earth indicate that its crust and mantle yield when unusual weight is placed on them.\n对地球重力场的研究表明，当被施加不寻常的重力时，地球的",
    "Sentence 09": "Quails typically have short rounded wings that enable them to spring into full flight instantly when disturbed in their hiding places.\n鹌鹑通常长有短而圆的翅膀，这一特点使它们可以在受到干扰",
    "Sentence 10": "Fungi are important in the process of decay, which returns ingredients to the soil, enhances soil fertility, and decomposes animal debris.\n真菌在腐化过程中十分重要，腐化过程将各种成分回馈于土",
    "Sentence 11": "Most substance contract when they freeze so that the density of a substance’s solid is higher than the density of its liquid.\n大多数物质冻结时会收缩，所以它们的密度在固态时高于液态",
    "Sentence 12": "By the middle of the twentieth century, painters and sculptors in the United States had begun to exert a great worldwide influence over art.\n到了20世纪中期，在美国的画家和雕塑家们开始在世界范围内",
    "Sentence 13": "Although apparently rigid, bones exhibit a degree of elasticity that enables the skeleton to withstand considerable impact.\n虽然骨头看起来坚硬，但它也显示出一定的弹性，使得骨骼能",
    "Sentence 14": "Finally, the coughing reflex in reaction to irritants in the airway produces not a cough during sleep but a cessation of breathing.\n最后，在应对呼吸道中的刺激物时，咳嗽反射引起的不是睡眠",
    "Sentence 15": "But when consumers do not know they are being lobbied, they may accept claims they would otherwise be suspicious of.\n但当消费者不知自己正被游说时，他们可能接受原本会表示怀",
    "Sentence 16": "Buyers and sellers should be aware of new developments in technology which can and does affect marketing activities.\n购买者和销售者都应该意识到技术方面的新发展，这些技术能",
    "Sentence 17": "With modern offices becoming more mechanized, designers are attempting to personalize them with warmer, less severe interiors.\n随着现代办公室变得越来越呆板，设计师们正尝试利用更加温",
    "Sentence 18": "The worker and soldier castes of termites consist of both males and females, and the queen lives permanently with a male consort.\n白蚁中的工蚁和兵蚁的阶层由雄性和雌性共同组成，而女王永",
    "Sentence 19": "Children with parents whose guidance is firm, consistent, and rational are inclined to possess high levels of self-confidence.\n父母的教导是坚定、始终如一和理性的，孩子就倾向于具有高",
    "Sentence 20": "Lucretia Mott’s influence was so significant that she has been credited by some authorities as the originator of feminism in the United States.\n路克瑞莎·马特的影响是如此巨大，以至于一些权威部门认定她",
    "Sentence 21": "No social crusade aroused Elizabeth Williams’ enthusiasm more than the expansion of educational facilities for immigrants to the United States.\n没有任何一项社会运动比给美国的移民增加教育设施更能激发",
    "Sentence 22": "Since wind-pollinated flowers have no need to attract insects or other animals, they have dispensed with bright petals, nectar, and scent.\n由于靠风传播授粉的花不需要吸引昆虫或其他动物，所以它们",
    "Sentence 23": "In the absence of a tradition of classical stone-carving and building, the desire to develop Roman amenities would have been difficult to fulfill.\n由于缺乏古典的石材雕刻和建筑的传统，开发罗马风格的便利",
    "Sentence 24": "Out in remote areas of the countryside, in rural locations, music was more traditional; the same songs were enjoyed by previous generations.\n在遥远偏僻的乡村，在农村地区，音乐更传统；同样的歌曲，",
    "Sentence 25": "In the second half of the millennium, in the south around the city of Uruk, there was an enormous escalation in the area occupied by permanent settlements.\n在一千年的后半段，在乌鲁克城南部，被永久定居点占用的地",
    "Sentence 26": "By fossils, we mean traces of prehistoric animals such as bones, which become mineralized, or impressions of bones or organs that are left in stone.\n提到化石，我们指的是史前生物的遗迹，比如已经矿化的骨",
    "Sentence 27": "The application of electronic controls made possible by the microprocessor and computer storage have multiplied the uses of the modern typewriter.\n借助微处理器和电脑存储，电子控制装置的运用成为可能，该",
    "Sentence 28": "Even though the precise qualities of hero in literary words may vary over time, the basic exemplary function of the hero seems to remain constant.\n即便文学语言中描述的英雄所具备的确切品质会随时代变化，",
    "Sentence 29": "When Henry Ford first sought financial backing for making cars, the very notion of farmers and clerks owning automobiles was considered ridiculous.\n当亨利·福特最初为制造汽车寻求资金支持时，人们觉得“农民和",
    "Sentence 30": "Many people who wanted to become archaeologists ended up pursuing other careers and contributing to archaeological research only as unpaid amateurs.\n很多想要成为考古学家的人最后都从事了其它的职业，只作为",
    "Sentence 31": "Even before the discovery of germs, beliefs that disease spread by “miasmas” （noxious forms of bad air） prompted attention to sewers and open garbage.\n甚至在发现细菌以前，疾病通过“瘴气”（有毒的恶性气体）传",
    "Sentence 32": "Since the consumer considers the best fruit to be that which is the most attractive, the grower must provide products that satisfy the discerning eye.\n因为顾客认为最好的水果应该是看起来最吸引人的，所以种植",
    "Sentence 33": "With no oceans to dissolve it, outgassed carbon dioxide began to accumulate in the atmosphere, intensifying the greenhouse effect even more.\n没有海洋溶解二氧化碳，排出的二氧化碳开始在大气中聚集，",
    "Sentence 34": "Buildings contribute to human life when they provide shelter, enrich space, complement their site, suit the climate, and are economically feasible.\n建筑物为人类生活贡献良多，它们提供遮蔽处，丰富活动空",
    "Sentence 35": "Research into the dynamics of storms is directed toward improving the ability to predict these events and thus to minimize damage and avoid loss of life.\n对风暴动力学的研究旨在提高对这类风暴事件预测的能力，从",
    "Sentence 36": "Their streamlined bodies, the absence of hind legs, and the presence of a fluke and blowhole cannot disguise their affinities with land dwelling mammals.\n它们呈流线型的身体，后腿的消失，尾片和气孔的出现，这些",
    "Sentence 37": "Scientists do not know why dinosaurs became extinct, but some theories postulate that changes in geography, climate, and sea levels were responsible.\n科学家们不知道恐龙为何灭绝了，但是一些理论推断这是地",
    "Sentence 38": "The elimination of inflation would ensure that the amount of money used in repaying a loan would have the same value as the amount of money borrowed.\n消除通货膨胀，可确保用来偿还贷款的钱与借贷的钱价值相",
    "Sentence 39": "Futurism, an early twentieth-century movement in art, rejected all traditions and attempted to glorify contemporary life by emphasizing the machine and motion.\n未来主义是20世纪早期的一股艺术思潮，它抛弃一切传统，试",
    "Sentence 40": "Acids are chemical compounds that, in water solution, have a sharp taste, a corrosive action on metals, and the ability to turn certain blue vegetable dyes red.\n酸是一种化合物，在溶于水时，它具有强烈的气味，对金属有",
    "Sentence 41": "In other instances, such as the Indus River Valley, the cities lacked a royal precinct and the ostentatious palaces that marked their contemporaries elsewhere.\n但其他情况下，比如在印度河流域，城市就没有像同时期其他",
    "Sentence 42": "Offshore drilling platforms extend the search for oil to the ocean’s continental shelves—those gently sloping submarine regions at the edges of the continents.\n近海钻探平台将寻找石油的区域延伸到了海洋大陆架上——陆",
    "Sentence 43": "Even those artists who were most dependent on photography became reluctant to admit that they made use of it, in case this compromised their professional standing.\n即使是那些对摄影术最为依赖的艺术家们也变得不愿意承认他",
    "Sentence 44": "According to anthropologists, the earliest ancestors of humans that stood upright resembled chimpanzees facially, with sloping foreheads and protruding brows.\n根据人类学家的说法，直立行走的最早的人类祖先的面部轮廓",
    "Sentence 45": "Anarchism is a term describing a cluster of doctrines and attitudes whose principal uniting feature is the belief that government is both harmful and unnecessary.\n无政府主义这个词描述的是一组学说和态度，它们的主要共同",
    "Sentence 46": "A rotary engine attached to the steam engine enabled shafts to be turned and machines to be driven, resulting in mills using steam power to spin and weave cotton.\n与蒸汽机相连的旋转式发动机带动轴承转动，从而驱动机器，",
    "Sentence 47": "Self-awareness, even in its earliest stages, might entail an awareness of others, the ability to see their perspective and to look at the world from another’s point of view.\n自我意识，即使是在最初的阶段，也可能涉及对其他人的感",
    "Sentence 48": "Various committees acted as an executive branch, implementing policies of the assembly and supervising, for instance, the food and water supplies and public buildings.\n各委员会作为一个行政部门贯彻执行议会政策，并对诸如食",
    "Sentence 49": "A mountain range may emerge and gradually split a population of organisms that can inhabit only lowland lakes; certain fish populations might become isolated in this way.\n一条山脉可能会出现，并逐渐隔绝一个仅在低地湖泊栖息的生",
    "Sentence 50": "Think of it this way, humans originally needed to have a stronger sensitivity to bitter-tasting foods so they could learn what plants were good for them and which ones might be poisonous.\n这样想想看，人类最初需要对苦味的食物更加敏感，这样他们",
    "Sentence 51": "Because eastern plows could not penetrate the densely tangled roots of prairie grass, the earliest settlers erected farms along the boundary separating the forest from the prairie.\n由于东方的犁无法穿透大草原那浓密缠结的草的根部，早期移",
    "Sentence 52": "If the artificial Sun remained stationary, the birds would shift their direction with respect to it at a rate of about 15 degrees per hour, the Sun’s rate of movement across the sky.\n如果人造太阳保持静止，这些鸟会以每小时15度的速度改变它",
    "Sentence 53": "The Industrial Revolution had several roots, one of which was a commercial revolution that, beginning as far back as the sixteenth century, accompanied Europe’s expansion overseas.\n工业革命有几个根源，其中之一就是商业革命，商业革命开始",
    "Sentence 54": "The jaw joints of many advanced herbivores, such as cows, lie at a different level than the tooth row, allowing transverse tearing, shredding, and compression of plant material.\n许多高级食草动物——比如牛——的颌关节和牙排位于不同的",
    "Sentence 55": "So musical instruments evolved in ways that optimize their acoustical properties—how the instrument vibrates and sends those vibration through the air to our eardrums.\n因此乐器的演变方式就是优化它们的声学特性，即乐器如何振",
    "Sentence 56": "German printers had the disadvantage of working with the complex typeface that the Italians sneeringly referred to as “Gothic” and that later became known as black letter.\n德国打印机的缺点是使用一种复杂的字体，意大利人嘲讽地称",
    "Sentence 57": "Elizabeth Blackwell, the first woman medical doctor in the United States, founded the New York Infirmary, an institution that has always had a completely female medical staff.\n美国第一位女医生伊丽莎白·布莱克威尔创建了纽约诊所，该机",
    "Sentence 58": "We’ve gone over where coral reefs are usually formed—along the edges of shallow ocean banks in tropical or subtropical regions, and the fact that they are declining at an alarming rate.\n我们已经讲过珊瑚礁通常在哪里形成——沿着热带或亚热带地",
    "Sentence 59": "Raised beaches often consist of areas of sand, pebbles, or dunes, sometimes containing seashells or piles of debris comprising shells and bones of marine animals used by humans.\n上升海滩通常由沙洲、鹅卵石或沙丘组成，有时包含贝壳或者",
    "Sentence 60": "But as more and more accumulations of strata were cataloged in more and more places, it became clear that the sequences of rocks sometimes differed from region to region and that no rock type was ever going to become a reliable time marker throughout the world.\n由于在越来越多的地方，越来越多的岩层积累形式被编入分",
    "Sentence 61": "This was an important innovation, because the camel’s abilities to thrive in harsh desert conditions and to carry large loads cheaply made it an effective and efficient means of transportation.\n这是一项重要革新，因为骆驼能在恶劣的沙漠环境繁衍生息，",
    "Sentence 62": "These people exploited the landscape intensively, foraging on hill slopes for wild cereal grasses and nuts, while hunting gazelle and other game on grassy lowlands and in river valleys.\n这些人对该地区进行了高强度的开发，他们在山坡上搜寻野生",
    "Sentence 63": "The recognition that many aspects of the modern flora and fauna were present on both sides of the Bering Sea as remnants of the ice-age landscape led to this region being named Beringia.\n人们认识到，作为冰河时代地貌的遗迹，现代植物群和动物群",
    "Sentence 64": "Thus, the recalling of an event （a hunt, battle, or other feat） is elaborated through the narrator’s pantomime and impersonation and eventually through each role being assumed by a different person.\n因此，在回忆一个事件时（一次打猎、战役或是其它功勋伟",
    "Sentence 65": "The extreme seriousness of desertification results from the vast areas of land and the tremendous numbers of people affected, as well as from the great difficulty of reversing or even slowing the process.\n沙漠化问题异常严重，这是因为有很广阔的地区和数量庞大的",
    "Sentence 66": "Before starting on a sea voyage, prudent navigators learn the sea charts, study the sailing directions, and memorize lighthouse locations to prepare themselves for any conditions they might encounter.\n谨慎的航海员在出航前，会学习海图，研究航向，并熟记灯塔",
    "Sentence 67": "The question of why infantile amnesia occurs has intrigued psychologists for decades, especially in light of ample evidence that infants and young children can display impressive memory capabilities.\n数十年来,为什么会发生婴儿期遗忘这个问题一直让心理学家们",
    "Sentence 68": "Researchers can drill core samples, uh, basically get a cross-section of a tree without having to kill it, look at the rings and get a picture of what the climate was like in the basin for each of the tree’s years.\n研究人员可以钻取芯部样本，基本上获取一棵树的横截面而不",
    "Sentence 69": "Great Britain’s better-developed banking and credit system also helped speed the industrial progress, as did the fact that it was the home of an impressive array of entrepreneurs and inventors.\n英国较成熟的银行和信贷体系也有助于加快工业进步，就像英",
    "Sentence 70": "Confronted with a multitude of unreliable figures, economists have compared the population records with the aggregate data for cultivated land area and grain production in the six centuries since 1368.\n面对大量不可靠的数字，经济学家将人口记录与1368年以来六",
    "Sentence 71": "Apparently, species-rich plots were likely to contain some droughtresistant plant species that grew better in drought years, compensating for the poor growth of less-tolerant species.\n显然，物种丰富的地块很可能包含一些抗旱植物品种，这些抗",
    "Sentence 72": "Even more shocking is the fact that the number and rate of imprisonment have more than doubled over the past twenty years, and recidivism—that is the rate for re-arrest—is more than 60 percent.\n更让人吃惊的事实是，监禁的数目和比率在过去20年里翻了一",
    "Sentence 73": "These plants propagate by producing spores—tiny fertilized cells that contain all the instructions for making a new plant—but the spores are unprotected by any outer coating and carry no supply of nutrient.\n这些植物通过产生孢子来繁殖——孢子是一些微小的已受精细",
    "Sentence 74": "Meanwhile, the deadliest strains of the virus perished with their hosts as natural selection favored strains that could infect hosts but not kill them. Thus, natural selection stabilized this host-parasite relationship.\n同时，由于自然选择更倾向于那些能够感染寄主但不致其死亡",
    "Sentence 75": "The residence time is the average length of time that any particular molecule of water remains in the lake, and it is calculated by dividing the volume of water in the lake by the rate at which water leaves the lake.\n停留时间指的是特定水分子在湖中停留的平均时长。这是通过",
    "Sentence 76": "An eye is a collection of cells that are specialized for light detection through the presence of photosensitive pigment as well as a means of restricting the direction of incoming light that will strike the photosensitive cells.\n眼睛由专门探测光源的细胞聚合而成，这些细胞通过使用光敏",
    "Sentence 77": "Sociologists view primary groups as bridges between individuals and the larger society because they transmit, mediate, and interpret a society’s cultural patterns and provide the sense of oneness so critical for social solidarity.\n社会学家将初级群体看作个体与更大的社会群体之间的桥梁，",
    "Sentence 78": "Importing the grain, which would have been expensive and time consuming for the Dutch to have produced themselves, kept the price of grain low and thus stimulated individual demand for other foodstuffs and consumer goods.\n荷兰人自己生产粮食既昂贵又费时，进口粮食使得粮食的价格",
    "Sentence 79": "While the men who make faithful copies of sand paintings from the past represent the principle of stability in Navajo thought, women embody dynamism and create new designs for every weaving they make.\n如实复制了过去的沙画的男人们代表着纳瓦霍人思想中的稳定",
    "Sentence 80": "In turn, a deep attachment to the land, and to the stability which rural life engenders, fostered the Roman virtues: gravitas, a sense of responsibility, pietas, a sense of devotion to family and country, and iustitia, a sense of the natural order.\n反过来，对土地以及乡村生活所带来的稳定性的深深依恋孕育",
    "Sentence 81": "In contrast to mammals and birds, amphibians are unable to produce thermal energy through their metabolic activity, which would allow them to regulate their body temperature independent of the surrounding or ambient temperature.\n与哺乳动物和鸟类相反，两栖类动物不能通过它们的代谢活动",
    "Sentence 82": "This is because the gaps among the original grains are often not totally plugged with cementing chemicals; also, parts of the original grains may become dissolved by percolating groundwater, either while consolidation is taking place or at any time afterwards.\n这是因为最初颗粒间的缝隙通常并未完全被黏固的化学物质塞",
    "Sentence 83": "The growth of mutual trust among merchants facilitated the growth of sales on credit and led to new developments in finance, such as the bill of exchange, a device that made the long, slow, and very dangerous shipment of coins unnecessary.\n商家之间相互信任的增长促进了信贷销售的增长，促使了金融",
    "Sentence 84": "Widely reported, if somewhat distrusted, accounts by figures like the famous traveler from Venice, Marco Polo, of the willingness of people in China to trade with Europeans and of the immensity of the wealth to be gained by such contact made the idea irresistible.\n据广泛报道，虽然可能不足为信，诸如威尼斯著名旅行家马可·",
    "Sentence 85": "In the wake of the Roman Empire’s conquest of Britain in the first century A.D., a large number of troops stayed in the new province, and these troops had a considerable impact on Britain with their camps, fortifications, and participation in the local economy.\n在公元1世纪罗马帝国征服英国之后，大量军队驻守在这片新省",
    "Sentence 86": "While many programs designed for preschoolers focus primarily on social and emotional factors, some are geared mainly toward promoting cognitive gains and preparing preschoolers for the formal instruction they will experience when they start kindergarten.\n许多为学龄前儿童设计的项目主要集中在社会因素和情感因素",
    "Sentence 87": "Hero compiled descriptions and sketches of 70 some clever little, mechanical devices, most of which utilized compressed air to cause water, or in some cases, wine to flow from one place to another, or sometimes to squirt or to make some kind of noise.\n希罗编纂了约70种灵巧的小型机械设备的说明和草图，其中大",
    "Sentence 88": "Introducing genetically modified trees, designed for fast growth and high yield in given geographic conditions, would satisfy the demand for wood in many of those areas and save the endangered native trees, which often include unique or rare species.\n引入那些在特定的地理条件下生长快、产量高的转基因树木会",
    "Sentence 89": "In the 1760s, James Watt perfected a separate condenser for the steam, so that the cylinder did not have to be cooled at every stroke; then he devised a way to make the piston turn a wheel and thus convert reciprocating （back and forth） motion into rotary motion.\n18世纪60年代，詹姆斯·瓦特完善了分离的蒸汽冷凝器，因此不",
    "Sentence 90": "Unlike short-term financial cooperation between investors for a single commercial undertaking, joint-stock companies provided permanent funding of capital by drawing on the investments of merchants and other investors who purchased shares in the company.\n与由投资者组成的以单个商业项目为目的的短期财团不同，股",
    "Sentence 91": "This was justified by the view that reflective practice could help teachers to feel more intellectually involved in their role and work in teaching and enable them to cope with the paucity of scientific fact and the uncertainty of knowledge in the discipline of teaching.\n这是合理的，因为人们认为反思实践可以帮助老师们更加理性",
    "Sentence 92": "There were no other large public buildings, suggesting that the priests who were in charge of the temples also were responsible for governing the city and organizing people to work in the fields and on irrigation projects building and maintaining systems of ditches and dams.\n没有其他大的公共建筑，这意味着主管寺庙的祭司也负责管理",
    "Sentence 93": "Inequalities of wealth and rank certainly exist, and have probably existed in most pastoralist societies, but except in periods of military conquest, they are normally too slight to generate the stable, hereditary hierarchies that are usually implied by the use of the term class.\n财富和地位上的不平等确实存在，而且可能存在于绝大多数游",
    "Sentence 94": "Many ecologists now think that the relative long-term stability of climax communities comes not from diversity but from the “patchiness” of the environment; an environment that varies from place to place supports more kinds of organisms than an environment that is uniform.\n现在很多生态学家们认为，顶极群落相对长期的稳定性并非来",
    "Sentence 95": "According to conventional theory, yawning takes place when people are bored or sleepy and serves the function of increasing alertness by reversing, through deeper breathing, the drop in blood oxygen levels that are caused by the shallow breathing that accompanies lack of sleep or boredom.\n根据传统理论，当人们无聊或者困倦时就会打哈欠，伴随睡眠",
    "Sentence 96": "Contrary to the arguments of some that much of the Pacific was settled by Polynesians accidentally marooned after being lost and adrift, it seems reasonable that this feat was accomplished by deliberate colonization expeditions that set out fully stocked with food and domesticated plants and animals.\n一些人认为，太平洋大部分地区都是波利尼西亚人在迷失、漂",
    "Sentence 97": "The Athenian philosopher Socrates （470-399 B.C.） was the first person in Greece to propose a morality based on individual conscience rather than the demands of the state, and for this he was accused of not believing in the city’s gods and so corrupting the youth, and he was condemned to death.\n雅典哲学家苏格拉底（公元前470-399年）是希腊第一个提出基",
    "Sentence 98": "Two additional kinds of evidence support the hypothesis that petroleum is a product of the decomposition of organic matter: oil possesses optical properties known only in hydrocarbons derived from organic matter, and oil contains nitrogen and certain compounds believed to originate only in living matter.\n还有两个证据支持“石油是有机物分解的产物”这一假设：石油",
    "Sentence 99": "Though it may be difficult to imagine from a later perspective, a strain of critical opinion in the 1920s predicted that sound film would be a technical novelty that would soon fade from sight, just as had many previous attempts, dating well back before the First World War, to link images with recorded sound.\n虽然从后来的视角来看也许难以想象，但是在20世纪20年代，",
    "Sentence 100": "Thanks to modern irrigation, crops now grow abundantly in areas where once nothing but cacti and sagebrush could live.\n受当代灌溉设施之赐，在原来只有仙人掌和灌木蒿才能生存的地",
  },
};

/**
 * Look up sentence text by unit name.
 * If groupName is provided, look up in that specific book.
 * If not provided, try all books (for backwards compatibility).
 * Returns { english, chinese } or null if not found.
 */
export function getSentenceText(unitName: string, groupName?: string): { english: string; chinese: string } | null {
  if (groupName) {
    const bookMap = SENTENCE_DATA[groupName];
    if (!bookMap) return null;
    const text = bookMap[unitName];
    if (!text) return null;
    const [english, chinese] = text.split("\n");
    return { english, chinese };
  }

  // No groupName: search all books
  for (const bookMap of Object.values(SENTENCE_DATA)) {
    const text = bookMap[unitName];
    if (text) {
      const [english, chinese] = text.split("\n");
      return { english, chinese };
    }
  }
  return null;
}
